print("^2Jim^7-^2JobGarage ^7v^41^7.^43^7.^42 ^7- ^2Job Garage Script by ^1Jimathy^7")

--[[	LIST OF POSSIBLE VEHICLE MODIFIERS   ]]--
-- Using these will change how each vehicle spawns
-- This can be used for making sure the vehicles comes out exactly how you want it to

-- CustomName = "Police Car", this will show a custom override name for your vehicles so you don't need to add them to your vehicles.lua
-- rank = { 2, 4 }, -- This specifes which grades can see it, and only these grades
-- grade = 4, -- This specifies the lowest grade and above that can see the vehicle
-- colors = { 136, 137 }, -- This is the colour index id of the vehicle, Primary and Secondary in that order
-- bulletproof = true, -- This determines if the tyres are bullet proof (don't ask me why, I was asked to add this)
-- livery = 1, -- This sets the livery id of the vehicle, (most mod menus would number them or have them in number order) 0 = stock
-- extras = { 1, 5 }, -- This enables the selected extras on the vehicle
-- performance = "max", this sets the stats to max if available
-- performance = { 2, 3, 3, 2, 4, true }, -- This allows more specific settings for each upgrade level, in order: engine, brakes, suspension, transmission, armour, turbo
-- trunkItems = { }, -- Use this to add items to the trunk of the vehicle when it is spawned

-- ANY VEHICLE, BOATS, POLICE CARS, EMS VEHICLES OR EVEN PLANES CAN BE ADDED.

Config = {
	Debug = false,  -- Enable to use debug features
	Notify = "qb",
	CarDespawn = true, -- Sends the vehicle to hell
	Locations = {
		{ 	zoneEnable = true,
			job = "police",
			garage = {
				spawn = vector4(435.41, -975.93, 25.31, 90.86),
				out = vector4(441.39, -974.78, 25.7, 178.49),
				list = {
					["police"] = {
						CustomName = "Police Car",
						livery = 5,
						extras = { 1, 2 },
						performance = "max",
						trunkItems = {
							{ name = "heavyarmor", amount = 2, info = {}, type = "item", slot = 1, },
							{ name = "empty_evidence_bag", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "police_stormram", amount = 1, info = {}, type = "item", slot = 3, },
						},
					},
				},
			},
		},
		{ 	zoneEnable = true,
			job = "ambulance",
			garage = {
				spawn = vector4(-623.71, -106.54, 38.15, 84.98),
				out = vector4(-623.62, -109.78, 38.15, 87.63),
				list = {
					["fd2"] = {
						CustomName = "Ambulance",
						livery = 0,
						extras = { 1, 2, 5, 6, 7, 8, 9, 12 },
						rank = { 1, 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["fordambo"] = {
						CustomName = "Ford Ambulance",
						livery = 0,
						extras = { 1, 2, 3, 5, 6, 7, 8, 9 },
						rank = { 1, 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["arroweng"] = {
						CustomName = "Ford Engine (R&B)",
						livery = 0,
						extras = { 11, 12 },
						rank = { 1, 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["fd1"] = {
						CustomName = "Fire Engine",
						livery = 0,
						extras = { 1, 2, 3, 4, 6, 7, 11 },
						rank = { 1, 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["arrowladder"] = {
						CustomName = "Ladder Truck (R&B)",
						livery = 0,
						extras = { 1, 4, 5 },
						rank = { 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["fdatv"] = {
						CustomName = "ATV",
						livery = 0,
						extras = { 1, 2 },
						rank = { 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["FD8"] = {
						CustomName = "Ford Explorer",
						livery = 0,
						extras = { 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
						rank = { 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["fd6"] = {
						CustomName = "Ford F150",
						livery = 0,
						extras = { 1, 3, 9, 11 },
						rank = { 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["fd13"] = {
						CustomName = "Chevy Tahoe",
						livery = 0,
						extras = { 2, 7 },
						rank = { 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["21firedurango"] = {
						CustomName = "Dudge Durango",
						livery = 0,
						extras = { 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
						rank = { 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["fdfmo1"] = {
						CustomName = "Investigator Unit",
						livery = 0,
						extras = { },
						rank = { 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["arrowrescue"] = {
						CustomName = "Tactical Rescue (R&B)",
						livery = 0,
						extras = { 11, 12 },
						rank = { 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["20ramambo"] = {
						CustomName = "2020 Ford Ambulance",
						livery = 0,
						extras = { 1, 2, 4, 5, 6, 8, 10 },
						rank = { 1, 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
				},
			},
		},
		{ 	zoneEnable = true,
			job = "ambulance",
			garage = {
				spawn = vector4(-492.09, -336.74, 34.37, 172.44),
				out = vector4(-487.64, -337.33, 34.5, 87.46),
				list = {
					["fd2"] = {
						CustomName = "Ambulance",
						livery = 0,
						extras = { 1, 2, 5, 6, 7, 8, 9, 12 },
						rank = { 1, 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["fordambo"] = {
						CustomName = "Ford Ambulance",
						livery = 0,
						extras = { 1, 2, 3, 5, 6, 7, 8, 9 },
						rank = { 1, 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["arroweng"] = {
						CustomName = "Ford Engine (R&B)",
						livery = 0,
						extras = { 11, 12 },
						rank = { 1, 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["fd1"] = {
						CustomName = "Fire Engine",
						livery = 0,
						extras = { 1, 2, 3, 4, 6, 7, 11 },
						rank = { 1, 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["arrowladder"] = {
						CustomName = "Ladder Truck (R&B)",
						livery = 0,
						extras = { 1, 4, 5 },
						rank = { 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["fdatv"] = {
						CustomName = "ATV",
						livery = 0,
						extras = { 1, 2 },
						rank = { 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["FD8"] = {
						CustomName = "Ford Explorer",
						livery = 0,
						extras = { 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
						rank = { 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["fd6"] = {
						CustomName = "Ford F150",
						livery = 0,
						extras = { 1, 3, 9, 11 },
						rank = { 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["fd13"] = {
						CustomName = "Chevy Tahoe",
						livery = 0,
						extras = { 2, 7 },
						rank = { 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["21firedurango"] = {
						CustomName = "Dudge Durango",
						livery = 0,
						extras = { 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
						rank = { 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["fdfmo1"] = {
						CustomName = "Investigator Unit",
						livery = 0,
						extras = { },
						rank = { 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["arrowrescue"] = {
						CustomName = "Tactical Rescue (R&B)",
						livery = 0,
						extras = { 11, 12 },
						rank = { 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["20ramambo"] = {
						CustomName = "2020 Ford Ambulance",
						livery = 0,
						extras = { 1, 2, 4, 5, 6, 8, 10 },
						rank = { 1, 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
				},
			},
		},
		{ 	zoneEnable = true,
			job = "ambulance",
			garage = {
				spawn = vector4(337.38, -579.4, 28.8, 337.02),
				out = vector4(339.12, -586.53, 28.8, 71.36),
				list = {
					["fd2"] = {
						CustomName = "Ambulance",
						livery = 0,
						extras = { 1, 2, 5, 6, 7, 8, 9, 12 },
						rank = { 1, 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["fordambo"] = {
						CustomName = "Ford Ambulance",
						livery = 0,
						extras = { 1, 2, 3, 5, 6, 7, 8, 9 },
						rank = { 1, 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["arroweng"] = {
						CustomName = "Ford Engine (R&B)",
						livery = 0,
						extras = { 11, 12 },
						rank = { 1, 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["fd1"] = {
						CustomName = "Fire Engine",
						livery = 0,
						extras = { 1, 2, 3, 4, 6, 7, 11 },
						rank = { 1, 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["arrowladder"] = {
						CustomName = "Ladder Truck (R&B)",
						livery = 0,
						extras = { 1, 4, 5 },
						rank = { 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["fdatv"] = {
						CustomName = "ATV",
						livery = 0,
						extras = { 1, 2 },
						rank = { 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["FD8"] = {
						CustomName = "Ford Explorer",
						livery = 0,
						extras = { 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
						rank = { 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["fd6"] = {
						CustomName = "Ford F150",
						livery = 0,
						extras = { 1, 3, 9, 11 },
						rank = { 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["fd13"] = {
						CustomName = "Chevy Tahoe",
						livery = 0,
						extras = { 2, 7 },
						rank = { 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["21firedurango"] = {
						CustomName = "Dudge Durango",
						livery = 0,
						extras = { 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
						rank = { 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["fdfmo1"] = {
						CustomName = "Investigator Unit",
						livery = 0,
						extras = { },
						rank = { 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["arrowrescue"] = {
						CustomName = "Tactical Rescue (R&B)",
						livery = 0,
						extras = { 11, 12 },
						rank = { 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["20ramambo"] = {
						CustomName = "2020 Ford Ambulance",
						livery = 0,
						extras = { 1, 2, 4, 5, 6, 8, 10 },
						rank = { 1, 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
				},
			},
		},
		{ 	zoneEnable = true,
			job = "ambulance",
			garage = {
				spawn = vector4(1658.14, 3669.71, 35.34, 299.47),
				out = vector4(1652.34, 3661.69, 35.34, 299.81),
				list = {
					["fd2"] = {
						CustomName = "Ambulance",
						livery = 0,
						extras = { 1, 2, 5, 6, 7, 8, 9, 12 },
						rank = { 1, 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["fordambo"] = {
						CustomName = "Ford Ambulance",
						livery = 0,
						extras = { 1, 2, 3, 5, 6, 7, 8, 9 },
						rank = { 1, 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["arroweng"] = {
						CustomName = "Ford Engine (R&B)",
						livery = 0,
						extras = { 11, 12 },
						rank = { 1, 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["fd1"] = {
						CustomName = "Fire Engine",
						livery = 0,
						extras = { 1, 2, 3, 4, 6, 7, 11 },
						rank = { 1, 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["arrowladder"] = {
						CustomName = "Ladder Truck (R&B)",
						livery = 0,
						extras = { 1, 4, 5 },
						rank = { 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["fdatv"] = {
						CustomName = "ATV",
						livery = 0,
						extras = { 1, 2 },
						rank = { 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["FD8"] = {
						CustomName = "Ford Explorer",
						livery = 0,
						extras = { 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
						rank = { 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["fd6"] = {
						CustomName = "Ford F150",
						livery = 0,
						extras = { 1, 3, 9, 11 },
						rank = { 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["fd13"] = {
						CustomName = "Chevy Tahoe",
						livery = 0,
						extras = { 2, 7 },
						rank = { 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["21firedurango"] = {
						CustomName = "Dudge Durango",
						livery = 0,
						extras = { 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
						rank = { 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["fdfmo1"] = {
						CustomName = "Investigator Unit",
						livery = 0,
						extras = { },
						rank = { 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["arrowrescue"] = {
						CustomName = "Tactical Rescue (R&B)",
						livery = 0,
						extras = { 11, 12 },
						rank = { 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["20ramambo"] = {
						CustomName = "2020 Ford Ambulance",
						livery = 0,
						extras = { 1, 2, 4, 5, 6, 8, 10 },
						rank = { 1, 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
				},
			},
		},
		{ 	zoneEnable = true,
			job = "ambulance",
			garage = {
				spawn = vector4(-277.65, 6319.54, 32.36, 225.92),
				out = vector4(-284.91, 6326.62, 32.43, 227.29),
				list = {
					["fd2"] = {
						CustomName = "Ambulance",
						livery = 0,
						extras = { 1, 2, 5, 6, 7, 8, 9, 12 },
						rank = { 1, 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["fordambo"] = {
						CustomName = "Ford Ambulance",
						livery = 0,
						extras = { 1, 2, 3, 5, 6, 7, 8, 9 },
						rank = { 1, 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["arroweng"] = {
						CustomName = "Ford Engine (R&B)",
						livery = 0,
						extras = { 11, 12 },
						rank = { 1, 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["fd1"] = {
						CustomName = "Fire Engine",
						livery = 0,
						extras = { 1, 2, 3, 4, 6, 7, 11 },
						rank = { 1, 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["arrowladder"] = {
						CustomName = "Ladder Truck (R&B)",
						livery = 0,
						extras = { 1, 4, 5 },
						rank = { 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["fdatv"] = {
						CustomName = "ATV",
						livery = 0,
						extras = { 1, 2 },
						rank = { 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["FD8"] = {
						CustomName = "Ford Explorer",
						livery = 0,
						extras = { 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
						rank = { 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["fd6"] = {
						CustomName = "Ford F150",
						livery = 0,
						extras = { 1, 3, 9, 11 },
						rank = { 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["fd13"] = {
						CustomName = "Chevy Tahoe",
						livery = 0,
						extras = { 2, 7 },
						rank = { 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["21firedurango"] = {
						CustomName = "Dudge Durango",
						livery = 0,
						extras = { 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
						rank = { 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["fdfmo1"] = {
						CustomName = "Investigator Unit",
						livery = 0,
						extras = { },
						rank = { 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["arrowrescue"] = {
						CustomName = "Tactical Rescue (R&B)",
						livery = 0,
						extras = { 11, 12 },
						rank = { 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["20ramambo"] = {
						CustomName = "2020 Ford Ambulance",
						livery = 0,
						extras = { 1, 2, 4, 5, 6, 8, 10 },
						rank = { 1, 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
				},
			},
		},
		{ 	zoneEnable = true,
			job = "ambulance",
			garage = {
				spawn = vector4(208.82, -1647.7, 29.8, 317.72),
				out = vector4(210.3, -1657.42, 29.8, 49.38),
				list = {
					["fd2"] = {
						CustomName = "Ambulance",
						livery = 0,
						extras = { 1, 2, 5, 6, 7, 8, 9, 12 },
						rank = { 1, 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["fordambo"] = {
						CustomName = "Ford Ambulance",
						livery = 0,
						extras = { 1, 2, 3, 5, 6, 7, 8, 9 },
						rank = { 1, 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["arroweng"] = {
						CustomName = "Ford Engine (R&B)",
						livery = 0,
						extras = { 11, 12 },
						rank = { 1, 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["fd1"] = {
						CustomName = "Fire Engine",
						livery = 0,
						extras = { 1, 2, 3, 4, 6, 7, 11 },
						rank = { 1, 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["arrowladder"] = {
						CustomName = "Ladder Truck (R&B)",
						livery = 0,
						extras = { 1, 4, 5 },
						rank = { 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["fdatv"] = {
						CustomName = "ATV",
						livery = 0,
						extras = { 1, 2 },
						rank = { 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["FD8"] = {
						CustomName = "Ford Explorer",
						livery = 0,
						extras = { 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
						rank = { 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["fd6"] = {
						CustomName = "Ford F150",
						livery = 0,
						extras = { 1, 3, 9, 11 },
						rank = { 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["fd13"] = {
						CustomName = "Chevy Tahoe",
						livery = 0,
						extras = { 2, 7 },
						rank = { 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["21firedurango"] = {
						CustomName = "Dudge Durango",
						livery = 0,
						extras = { 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
						rank = { 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["fdfmo1"] = {
						CustomName = "Investigator Unit",
						livery = 0,
						extras = { },
						rank = { 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["arrowrescue"] = {
						CustomName = "Tactical Rescue (R&B)",
						livery = 0,
						extras = { 11, 12 },
						rank = { 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["20ramambo"] = {
						CustomName = "2020 Ford Ambulance",
						livery = 0,
						extras = { 1, 2, 4, 5, 6, 8, 10 },
						rank = { 1, 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
				},
			},
		},
		{ 	zoneEnable = true,
			job = "ambulance",
			garage = {
				spawn = vector4(1200.76, -1469.01, 34.86, 359.0),
				out = vector4(1208.19, -1475.13, 34.86, 89.03),
				list = {
					["fd2"] = {
						CustomName = "Ambulance",
						livery = 0,
						extras = { 1, 2, 5, 6, 7, 8, 9, 12 },
						rank = { 1, 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["fordambo"] = {
						CustomName = "Ford Ambulance",
						livery = 0,
						extras = { 1, 2, 3, 5, 6, 7, 8, 9 },
						rank = { 1, 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["arroweng"] = {
						CustomName = "Ford Engine (R&B)",
						livery = 0,
						extras = { 11, 12 },
						rank = { 1, 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["fd1"] = {
						CustomName = "Fire Engine",
						livery = 0,
						extras = { 1, 2, 3, 4, 6, 7, 11 },
						rank = { 1, 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["arrowladder"] = {
						CustomName = "Ladder Truck (R&B)",
						livery = 0,
						extras = { 1, 4, 5 },
						rank = { 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["fdatv"] = {
						CustomName = "ATV",
						livery = 0,
						extras = { 1, 2 },
						rank = { 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["FD8"] = {
						CustomName = "Ford Explorer",
						livery = 0,
						extras = { 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
						rank = { 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["fd6"] = {
						CustomName = "Ford F150",
						livery = 0,
						extras = { 1, 3, 9, 11 },
						rank = { 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["fd13"] = {
						CustomName = "Chevy Tahoe",
						livery = 0,
						extras = { 2, 7 },
						rank = { 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["21firedurango"] = {
						CustomName = "Dudge Durango",
						livery = 0,
						extras = { 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
						rank = { 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["fdfmo1"] = {
						CustomName = "Investigator Unit",
						livery = 0,
						extras = { },
						rank = { 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["arrowrescue"] = {
						CustomName = "Tactical Rescue (R&B)",
						livery = 0,
						extras = { 11, 12 },
						rank = { 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
					["20ramambo"] = {
						CustomName = "2020 Ford Ambulance",
						livery = 0,
						extras = { 1, 2, 4, 5, 6, 8, 10 },
						rank = { 1, 2, 3, 4, 5, 6, 7 },
						performance = "max",
						trunkItems = {
							{ name = "firstaid", amount = 6, info = {}, type = "item", slot = 1, },
							{ name = "bandage", amount = 10, info = {}, type = "item", slot = 2, },
							{ name = "ifaks", amount = 2, info = {}, type = "item", slot = 3, },
							{ name = "painkillers", amount = 10, info = {}, type = "item", slot = 4, },
						},
					},
				},
			},
		}
	},
}
